{
	"schema_version": "1.4.0",
	"id": "GHSA-vm8q-m57g-pff3",
	"modified": "2024-03-18T20:36:41Z",
	"published": "2024-03-15T21:30:43Z",
	"aliases": [
		"CVE-2024-27351"
	],
	"summary": "Regular expression denial-of-service in Django",
	"details": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "django"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "3.2"
						},
						{
							"fixed": "3.2.25"
						}
					]
				}
			],
			"ecosystem_specific": {
				"affected_functions": [
					"django.utils.text.Truncator.words"
				]
			}
		},
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "django"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "4.2"
						},
						{
							"fixed": "4.2.11"
						}
					]
				}
			],
			"ecosystem_specific": {
				"affected_functions": [
					"django.utils.text.Truncator.words"
				]
			}
		},
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "django"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "5.0"
						},
						{
							"fixed": "5.0.3"
						}
					]
				}
			],
			"ecosystem_specific": {
				"affected_functions": [
					"django.utils.text.Truncator.words"
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-27351"
		},
		{
			"type": "WEB",
			"url": "https://docs.djangoproject.com/en/5.0/releases/security"
		},
		{
			"type": "PACKAGE",
			"url": "https://github.com/django/django"
		},
		{
			"type": "WEB",
			"url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-47.yaml"
		},
		{
			"type": "WEB",
			"url": "https://groups.google.com/forum/#%21forum/django-announce"
		},
		{
			"type": "WEB",
			"url": "https://www.djangoproject.com/weblog/2024/mar/04/security-releases"
		}
	],
	"database_specific": {
		"cwe_ids": [
			"CWE-1333"
		],
		"github_reviewed": true,
		"github_reviewed_at": "2024-03-18T20:36:41Z",
		"nvd_published_at": "2024-03-15T20:15:09Z",
		"severity": "LOW"
	}
}
